# Generated by Django 4.2.11 on 2024-04-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('dt_nasc', models.DateField()),
                ('telefone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
