# Generated by Django 3.2.12 on 2024-03-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=32)),
                ('dt_nasc', models.DateField(default=False)),
                ('telefone', models.IntegerField(default=False)),
                ('cpf', models.IntegerField(default=False, max_length=12)),
            ],
        ),
    ]
